### ISSUE TITLE
Urgent need for the instruction sgt

### ISSUE THREAD

**Issue by huagailuowen** [DarkSharpness/REIMU#4]
It seems like that the "sgt" and "slt" instruction is not available in the current version.

**Comment by DarkSharpness** [comment]
Hi!

First of all, our simulator **does support** `slt` at present. And it seems that there's no such pseudo-instruction like `sgt` in the RISC-V spec (see Chapter 20 **RISC-V Assembly Programmer’s Handbook** of [this link](https://riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf)).

Anyway, whenever you need a command like `sgt rd, rs1, rs2`, you can always replace that with `slt rd, rs2, rs1`.
